// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XTCiOSSampleProject
{
	public partial class ViewDataSampleController : UIViewController
	{
		public ViewDataSampleController () : base ("ViewDataSampleController", null)
		{
			Title = "View Data";
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.dateLabel.Text = Settings.PickedTime.ToString ("dd/MM/yyyy");
			this.timeLabel.Text = Settings.PickedTime.ToString ("h:mm tt");
			this.radioSelectedLabel.Text = Settings.RadioSelectedValue;
			this.checkboxLabel.Text = Settings.CheckBoxSelected ? "T" : "F";
			this.seekBarProgressLabel.Text = Settings.SeekBarProgress.ToString ();
		}
	}
}
