// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XTCiOSSampleProject
{
	public partial class ViewsSampleController : UIViewController
	{
		public class TableSource : UITableViewSource
		{
			string[] items = new string[] { "Choose", "Or choose not" };
			int selected = -1;
			const string cellIdentifier = "TableCell";

			public override nint RowsInSection (UITableView tableview, nint section)
			{
				return items.Length;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
				// if there are no cells to reuse, create a new one
				if (cell == null) {
					cell = new UITableViewCell (UITableViewCellStyle.Default, cellIdentifier);
				}
				cell.TextLabel.Text = items[indexPath.Row];
				cell.Selected = (selected == indexPath.Row);
				return cell;
			}
		}

		public ViewsSampleController () : base ("ViewsSampleController", null)
		{
			Title = "Views Sample";
		}

		public override void ViewDidLoad()
		{
			slider.ValueChanged += (object sender, EventArgs e) => {
				sliderLabel.Text = slider.Value.ToString();
			};

			sliderLabel.Text = slider.Value.ToString();

			table.Source = new TableSource ();
			this.cancelButton.TouchUpInside += (object sender, EventArgs e) => NavigationController.PopViewController(true);
			this.saveButton.TouchUpInside += (object sender, EventArgs e) => {
				Settings.RadioSelectedValue = (new string[]{"A", "B", "C"})[this.segmentedControl.SelectedSegment];
				Settings.CheckBoxSelected = this.checkbox.On;
				Settings.SeekBarProgress = (int) this.slider.Value;

				NavigationController.PopViewController (true);
			};
		}
	}
}
