// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XTCiOSSampleProject
{
	public partial class OrientationsSampleController : UIViewController
	{
		public OrientationsSampleController () : base ("OrientationsSampleController", null)
		{
			Title = "Orientations";
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			portraitButton.TouchUpInside += (object sender, EventArgs e) => PresentModalViewController (new PortraitOrientationController (), true);
			portraitUpsideDownButton.TouchUpInside += (object sender, EventArgs e) => PresentModalViewController (new PortraitUpsideDownController (), true);
			landscapeLeftButton.TouchUpInside += (object sender, EventArgs e) => PresentModalViewController (new LandscapeOrientationController (), true);
			landscapeRightButton.TouchUpInside += (object sender, EventArgs e) => PresentModalViewController (new LandscapeUpsideDownController (), true);
		}
	}
}
