// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XTCiOSSampleProject
{
	public partial class PortraitOrientationController : UIViewController
	{
		public PortraitOrientationController () : base ("PortraitOrientationController", null)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			backButton.TouchUpInside += (object sender, EventArgs e) => DismissViewController (true, null);
		}

		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations ()
		{
			return UIInterfaceOrientationMask.Portrait;
		}
	}
}
